import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <section className="about pb-sm-5 ">
      <Head>
        <title>Yasin Özgür Çakmak</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container row mx-auto d-flex align-items-center mt-sm-4  mt-md-9">
        <p className="col-sm-12 col-lg-8 ">
          I am developing Frontend projects and learning new technologies to
          improve myself and gain experience in this field. I built applications
          with these technologies which you can find on my GitHub profile.
          <br />
          My career goal is to be a Frontend developer. In the following years,
          I want to learn backend technologies and become a full-stack
          developer.
        </p>
        <div className="col-sm-12 col-lg-4">
          <Image
            src="/development.jpeg"
            className="rounded w-100 h-50"
            width={300}
            height={200}
          />
        </div>
      </div>
    </section>
  );
}
